" General
set nocompatible
filetype off
" set rtp+=~/.vim/bundle/Vundle.vim

call plug#begin()
Plug 'flrnprz/candid.vim'
" Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
" Plug 'Valloric/YouCompleteMe', { 'do': './install.py --tern-completer' }
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'dyng/ctrlsf.vim'
Plug 'w0rp/ale'
Plug 'yegappan/grep'
Plug 'scrooloose/nerdtree'
Plug 'ctrlpvim/ctrlp.vim'
" Plug 'bling/vim-airline'
" Plug 'vim-airline/vim-airline-themes'
" Plug 'terryma/vim-multiple-cursors'
Plug 'airblade/vim-gitgutter'
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'jparise/vim-graphql'
Plug 'tveskag/nvim-blame-line'
Plug 'moll/vim-node'
Plug 'prettier/vim-prettier', { 'do': 'yarn install' }
" Add other plugins here
call plug#end()

let g:candid_color_store = {
    \ "black": {"gui": "#a8a19f", "cterm256": "0"},
    \ "white": {"gui": "#a8a19f", "cterm256": "15"},
    \ "red": {"gui": "#a8a19f", "cterm256": "1"},
    \ "purple": {"gui": "#a8a19f", "cterm256": "4"},
    \ "cyan": {"gui": "#a8a19f", "cterm256": "4"},
    \ "green": {"gui": "#a8a19f", "cterm256": "2"},
    \ "comment": {"gui": "#a8a19f", "cterm256": "7"},
    \}

set backspace=indent,eol,start
set history=1000
set showcmd
set showmode
set autoread
set hidden

" UI
set laststatus=2
set ruler
set wildmenu
colorscheme candid
set background=dark
set number
set relativenumber
set title
set mouse=a

" Swap & backups
set noswapfile
set nobackup
set nowb

" Indentation
set autoindent
filetype plugin indent on
set expandtab
set tabstop=2
set shiftwidth=2
set nowrap

" Search
set incsearch
set hlsearch
set ignorecase
set smartcase

" Text rendering
set encoding=utf-8
set linebreak
set scrolloff=3
set sidescrolloff=5
syntax enable

set statusline=%F%m%r%h%w%=(%{&ff}/%Y)\ (line\ %l\/%L,\ col\ %c)\
set wildmenu
hi StatusLine ctermbg=black ctermfg=darkCyan
hi StatusLineNC ctermbg=black ctermfg=white

let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_ngdoc = 1
let g:netrw_liststyle = 3
let g:netrw_browse_split = 2
let g:netrw_winsize = 20
let g:deoplete#enable_at_startup = 1

" let g:airline_theme='simple'

hi Normal guibg=NONE ctermbg=NONE
highlight Visual cterm=NONE ctermbg=239 ctermfg=NONE

autocmd FileType javascript set formatprg=prettier\ --stdin
autocmd vimenter * NERDTree | wincmd p
autocmd BufEnter * EnableBlameLine
autocmd User Node
  \ if &filetype == "javascript" |
  \   nmap <buffer> <C-w>f <Plug>NodeVSplitGotoFile |
  \   nmap <buffer> <C-w><C-f> <Plug>NodeVSplitGotoFile |
	\ endif

nmap     <C-F>f <Plug>CtrlSFPrompt                  
nmap     <C-F>n <Plug>CtrlSFCwordPath
nmap     <C-F>p <Plug>CtrlSFPwordPath
